### ISSUE TITLE
define function

### ISSUE THREAD

**Issue by lassik** [dylan-lang/dylan-reference-manual#13]
I cannot find an explanation of what `define function` does in the manual. How does it differ from `define method`?

`define function` is used [here](https://github.com/dylan-lang/strings/blob/master/strings.dylan#L665) for example.

**Comment by waywardmonkeys** [comment]
https://opendylan.org/proposals/dep-0002-define-function.html

**Comment by cgay** [comment]
See also: https://opendylan.org/library-reference/language-extensions/define-function.html#function-definition

**Comment by cgay** [comment]
Closing this, as it's not an actual bug in the DRM.
