### ISSUE TITLE
local view

### ISSUE THREAD

**Issue by xieyuheng** [dylan-lang/dylan-reference-manual#5]
the links do not work when view the html files locally in a browser.

what should I do to view them locally ?

**Comment by waywardmonkeys** [comment]
We really should probably modify the pages to use regular links and not ones that rely upon content negotiation. This is a pretty annoying behavior of the current arrangement.

**Comment by xieyuheng** [comment]
HyperSpec is a good html doc for common lisp

http://www.lispworks.com/documentation/HyperSpec/Front/Hilights.htm

[specially good when viewed in the w3m of emacs]

dylan's html doc can only be better ^-^

**Comment by xieyuheng** [comment]
closing old issues :)
